# version: "3"
# services:
#   postgres:
#     image: postgres:12.1-alpine
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#   web:
#     build: .
#     volumes:
#       - .:/app/app/
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgres
version: '3'
services:
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      - SQLITE_PATH=/sqlite.db
  
    volumes:
      - ".:/app/"
      - "./data/sqlite.db:/sqlite.db"
            